name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build - std,serde
      run: cargo build --verbose --all-features
    - name: Run tests - std,serde
      run: cargo test --verbose --all-features
    - name: Build - no features
      run: cargo build --verbose --no-default-features
    - name: Run tests - no features
      run: cargo test --verbose --no-default-features
